#!/bin/bash

# Deployment Ready Hook - Triggered when odoo.sh deployment is ready
# This hook automatically starts testing when deployment monitoring detects readiness

HOOK_NAME="deployment-ready-odoo"
CLAUDE_CONFIG_DIR=".claude/config"
LOG_FILE="$CLAUDE_CONFIG_DIR/deployment-hooks.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Function to log messages
log_message() {
    echo "[$TIMESTAMP] $HOOK_NAME: $1" | tee -a "$LOG_FILE"
}

# Function to read deployment ready trigger
read_deployment_trigger() {
    local trigger_file="$CLAUDE_CONFIG_DIR/deployment-ready-trigger"
    
    if [ ! -f "$trigger_file" ]; then
        return 1
    fi
    
    # Extract deployment info
    if command -v jq >/dev/null 2>&1; then
        export DEPLOYMENT_SSH_HOST=$(jq -r '.ssh_host' "$trigger_file")
        export DEPLOYMENT_MODULES=$(jq -r '.modules' "$trigger_file")
        export DEPLOYMENT_DURATION=$(jq -r '.monitoring_duration' "$trigger_file")
    else
        # Fallback to simple parsing
        export DEPLOYMENT_SSH_HOST=$(grep '"ssh_host"' "$trigger_file" | cut -d'"' -f4)
        export DEPLOYMENT_MODULES=$(grep '"modules"' "$trigger_file" | cut -d'"' -f4)
        export DEPLOYMENT_DURATION=$(grep '"monitoring_duration"' "$trigger_file" | cut -d':' -f2 | tr -d ' ,')
    fi
    
    # Clean up trigger file
    rm "$trigger_file"
    
    return 0
}

# Function to execute automated testing
execute_automated_testing() {
    log_message "Starting automated testing suite"
    log_message "Target: $DEPLOYMENT_SSH_HOST"
    log_message "Modules: $DEPLOYMENT_MODULES"
    
    # Create testing script
    local test_script="$CLAUDE_CONFIG_DIR/automated-test-$$.sh"
    
    cat > "$test_script" << 'EOF'
#!/bin/bash

SSH_HOST="$1"
MODULES="$2"
LOG_FILE="$3"

log_test() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] AUTO-TEST: $1" >> "$LOG_FILE"
}

log_test "=== Automated Testing Started ==="
log_test "SSH Host: $SSH_HOST"
log_test "Modules: $MODULES"

# Convert comma-separated modules to array
IFS=',' read -ra MODULE_ARRAY <<< "$MODULES"

# Test results tracking
declare -A test_results
total_tests=0
passed_tests=0

# Test each module
for module in "${MODULE_ARRAY[@]}"; do
    module=$(echo "$module" | xargs)  # Trim whitespace
    if [ -n "$module" ]; then
        total_tests=$((total_tests + 1))
        log_test "Testing module: $module"
        
        # Execute test with timeout
        if timeout 300 ssh "$SSH_HOST" "odoo-bin --test-enable --test-tags=$module --stop-after-init --log-level=test" >/dev/null 2>&1; then
            log_test "✅ $module: PASSED"
            test_results["$module"]="PASSED"
            passed_tests=$((passed_tests + 1))
        else
            log_test "❌ $module: FAILED"
            test_results["$module"]="FAILED"
        fi
    fi
done

# Calculate success rate
if [ $total_tests -gt 0 ]; then
    success_rate=$((passed_tests * 100 / total_tests))
else
    success_rate=0
fi

log_test "=== Testing Summary ==="
log_test "Total modules: $total_tests"
log_test "Passed: $passed_tests"
log_test "Success rate: ${success_rate}%"

# Generate detailed report
REPORT_FILE="$CLAUDE_CONFIG_DIR/deployment-test-report-$(date +%Y%m%d-%H%M%S).md"

cat > "$REPORT_FILE" << EOT
# 🧪 Automated Deployment Testing Report

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**Environment**: $SSH_HOST  
**Trigger**: Deployment Ready Hook  

## 📊 Test Summary

- **Total Tests**: $total_tests
- **Passed**: $passed_tests  
- **Failed**: $((total_tests - passed_tests))
- **Success Rate**: ${success_rate}%

## 📋 Module Test Results

EOT

# Add individual module results
for module in "${MODULE_ARRAY[@]}"; do
    module=$(echo "$module" | xargs)
    if [ -n "$module" ]; then
        status="${test_results[$module]}"
        if [ "$status" = "PASSED" ]; then
            echo "- ✅ **$module**: PASSED" >> "$REPORT_FILE"
        else
            echo "- ❌ **$module**: FAILED" >> "$REPORT_FILE"
        fi
    fi
done

cat >> "$REPORT_FILE" << EOT

## 🔗 Quick Actions

\`\`\`bash
# View detailed logs
ssh $SSH_HOST "tail -100 ~/logs/odoo.log"

# Re-run failed tests
ssh $SSH_HOST "odoo-bin --test-enable --test-tags=FAILED_MODULE --stop-after-init --log-level=test"

# Access Odoo shell for debugging
ssh $SSH_HOST "odoo-bin shell"
\`\`\`

## 📈 Next Steps

EOT

if [ $success_rate -ge 80 ]; then
    cat >> "$REPORT_FILE" << EOT
✅ **Deployment Successful** - Ready for use
- All critical tests passed
- Services are stable and operational
- Consider production deployment if this is staging

EOT
else
    cat >> "$REPORT_FILE" << EOT
⚠️ **Issues Detected** - Manual review required
- Some tests failed, investigation needed
- Review logs for error details
- Fix issues before proceeding to production

EOT
fi

echo "---" >> "$REPORT_FILE"
echo "*Report generated by Claude Code Deployment Hook*" >> "$REPORT_FILE"

log_test "Test report generated: $REPORT_FILE"

# Create notification trigger for Claude Code
NOTIFICATION_TRIGGER="$CLAUDE_CONFIG_DIR/test-completion-trigger"
cat > "$NOTIFICATION_TRIGGER" << EOT
{
  "event": "testing_completed",
  "timestamp": "$(date -Iseconds)",
  "ssh_host": "$SSH_HOST",
  "modules": "$MODULES",
  "total_tests": $total_tests,
  "passed_tests": $passed_tests,
  "success_rate": $success_rate,
  "report_file": "$REPORT_FILE"
}
EOT

log_test "=== Automated Testing Completed ==="
exit 0
EOF

    chmod +x "$test_script"
    
    # Execute testing in background
    nohup bash "$test_script" "$DEPLOYMENT_SSH_HOST" "$DEPLOYMENT_MODULES" "$LOG_FILE" >/dev/null 2>&1 &
    local test_pid=$!
    
    log_message "Automated testing started with PID: $test_pid"
    echo "$test_pid" > "$CLAUDE_CONFIG_DIR/automated-test.pid"
    
    return 0
}

# Function to notify user about testing start
notify_testing_start() {
    cat << EOF

🧪 HOOK ACTIVATED: Automated Testing Started
════════════════════════════════════════════

📋 Testing Details:
   • Trigger: Deployment Ready Detection
   • Environment: $DEPLOYMENT_SSH_HOST
   • Modules: $DEPLOYMENT_MODULES
   • Deployment Duration: ${DEPLOYMENT_DURATION}s

⏳ Testing in Progress:
   • Automated test suite: RUNNING
   • Progress monitoring: ACTIVE
   
🔄 What's happening:
   1. Testing each module individually
   2. Generating comprehensive test report
   3. Will notify when testing completes
   
📊 Monitor progress:
   tail -f $LOG_FILE

EOF
}

# Main hook execution
main() {
    log_message "=== Deployment Ready Hook Started ==="
    
    # Read deployment trigger
    if ! read_deployment_trigger; then
        log_message "No deployment ready trigger found, exiting"
        exit 0
    fi
    
    log_message "Deployment ready trigger detected"
    log_message "SSH Host: $DEPLOYMENT_SSH_HOST"
    log_message "Modules: $DEPLOYMENT_MODULES"
    log_message "Deployment took: ${DEPLOYMENT_DURATION}s"
    
    # Execute automated testing
    if execute_automated_testing; then
        log_message "Automated testing initiated successfully"
        
        # Notify user
        notify_testing_start
        
        log_message "=== Deployment Ready Hook Completed ==="
        exit 0
    else
        log_message "Failed to start automated testing"
        exit 1
    fi
}

# Execute main function
main "$@"